### ISSUE TITLE
Call out v0 to v1 changes

### ISSUE THREAD

**Issue by stramel** [Polymer/polymer-linter#142]
It would be nice to have linter warn and be able to fix some of the easy v0 to v1 spec changes with some Polymer changes that would allow Polymer v1 (P1) components to work with Polymer v2 (P2) legacy. These changes should allow P1 components to work with P2 without going into the full hybrid setup.

### CSS

- [x] `@apply(--foo);` to `@apply --foo;`
- [x] `var(--a, --b)` to `var(--a, var(--b))`
- [x] `:root` to `html` or `:root` to `:host > *` depending on location (shadow root vs main document) ~(#168)~
- [x] `::content` to `::slotted` ~(#160)~
- [x] `::shadow` and `/deep/` removed ~(#6) (#158)~

### HTML

- [x] `<content>` to `<slot>` (Currently listed under Polymer)
    - [x] Warns
    - [x] Fixable
- [x] `<style>` tags moved inside `<template>`

### Polymer

- [x] `document.createElement('style', 'custom-style')` not allowed anymore ~(#163)~
- [x] `is="custom-style"` to be wrapped with `<custom-style>` if not within `<template>` ~(#155)~ ~(#166)~
- [x] Check that `dom-module` has `id` attribute instead of `is` or `name`
    - [x] Warns
    - [x] Fixable ~(#162)~

Possible Additional ones
Ensure semi-colon on CSS Mixin declarations
`Polymer.dom` returns `NodeList` instead of `Array` (**NOTE:** May be difficult to detect)
`:host-context([dir=rtl]))` to `:dir(rtl)` (**NOTE:** Only available in Firefox)
`lazyRegister` no longer exists (**NOTE:** Not sure this should be a lint rule)
`this.customStyle['--my-toolbar-color'] = 'blue';` to `this.updateStyles({'--my-toolbar-color': 'blue'});`

**Comment by stramel** [comment]
# Upgrade Cheatsheet
This is a simplified version of https://www.polymer-project.org/2.0/docs/upgrade. It also lists what warnings and fixes are available for each upgrade task.

## Shadow DOM template and styling

### DOM Template

- `<dom-module>` using `is` or `name` should be replaced to use `id`
	- Warns
	- Fixable: Except `dom-module`s that contain both `name` and `is`
- Move `<style>` tags inside the `<template>`
	- Warns
	- Fixable
- Update your element's DOM template to use the new `<slot>` element instead of `<content>`
	- Warns
	- Fixable: Except advanced usages including stamping templates
- Update any URLs inside the template.
	- Future: Potentially warn/fix missing `importPath` and `rootPath`

### Shadow DOM Styles

- Update styles to use the `::slotted()` selector in place of `::content`
	- Warns
	- Fixable: Except deeper than first descendant
	- Future: Potentially warn on selectors after `::slotted()`
- Remove any `/deep/` and `::shadow` CSS rules
	- Warns
- Remove :root selectors (#168)
	- Warns
	- Fixable
- Update custom property syntax
	- Warns
	- Fixable
- Wrap `custom-style` elements (#166)
	- Warns
	- Fixable

## DOM APIs

### Hybrid Elements

- `Polymer.dom` returns `NodeList` now instead of `Array`


### Class-based elements

- Don't use `Polymer.dom`
- Use `this.shadowRoot` in place of `Polymer.dom(this.root)`
	- Future: Potentially, convert usage
- For events, use the standard v1 event API
	- Warns
	- Future: Potentially, fixable
- The `Polymer.FlattenedNodesObserver` class can be used to replace the 1.x `observeNodes` method
- Replace the `getEffectiveChildren` method, use the `getFlattenedNodes` helper method, and filter down to just the elements
- Replace the `getContentChildren` method, write platform code to perform this functionality (get the `assignedNodes`, and filter down to just the elements)

## CSS custom property shim

### Class-based elements

- The `customStyle` instance property has been removed. Use `updateStyles` instead.

**Comment by stramel** [comment]
This covers the majority of v0 to v1 changes.

**Comment by rictic** [comment]
Awesome work @stramel!!
